import App from "@/components/ContactPage/App";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Solar Components - Kontakt",
  description: "Generated by create next app",
}

export default function Contact() {
  return <App />
}
