import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import PageTransition from "./PageTransition";
import PageInitialAnimation from "./PageInitialAnimation";

const roboto = Roboto({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: "Solar Components",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <body className={roboto.className}>
        <ReduxProvider>
          <PageInitialAnimation>
            <Header />
            <PageTransition>
                {children}
            </PageTransition>
            <Footer />
          </PageInitialAnimation>
        </ReduxProvider>
      </body>
    </html>
  );
}
