import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";
import FetchFromServerComponent from "./FetchFromServerComponent";

const roboto = Roboto({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: "Solar Components",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs">
      <body className={roboto.className}>
        <FetchFromServerComponent>
          {children}
        </FetchFromServerComponent>
      </body>
    </html>
  );
}
