import App from "@/components/ConditionsPage/App";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Solar Components - Podminky",
  description: "Generated by create next app",
}

export default function Inquiry() {
  return <App />
}
