import App from "@/components/PruductsPage/App";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Solar Components - Produkty",
  description: "Generated by create next app",
}

export default function Products() {
  return <App />
}
